services:
  - name: fastapi-book
    type: web
    env: docker
    repo: https://github.com/LmOpe/fastapi-book-project
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000

  - name: nginx-proxy
    type: web
    env: docker
    repo: https://github.com/LmOpe/fastapi-book-project
    plan: free
    dockerfilePath: ./nginx.Dockerfile
    envVars:
      - key: BACKEND_URL
        fromService:
          name: fastapi-book
          type: web
          property: hostport
    
    startCommand: |
      echo "Pinging backend at $BACKEND_URL"
      curl -v $BACKEND_URL || echo "Backend unreachable!"