name: Deploy on Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via Docker
        run: |
          cd ~/fastapi-book-project || exit 1
          git pull origin main || exit 1
          docker-compose down || exit 1
          docker-compose up -d || exit 1
