name: Deploy on Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$GCE_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH to Google Cloud Platform compute instances
        uses: google-github-actions/ssh-compute@v1.1.3
        with:
          project_id: ${{ secrets.GCE_PROJECT_ID }}
          zone: ${{ secrets.GCE_ZONE }}
          instance_name: ${{ secrets.GCE_INSTANCE_NAME }}
          ssh_private_key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          script: |
            pwd
            ls -lah
            cd fastapi-book-project
            git pull origin main
            docker-compose down
            docker-compose up -d
