name: Run Tests

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Code
              uses: actions/checkout@v4

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
                cache: "pip"
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install -r requirements.txt
            
            - name: Run Pytest
              run: pytest